### PR TITLE
feature: upload dynamic icon in isolation

### PR DESCRIPTION
**Pull request by isArlekin**
What was done is scope of this task?

`packages/react-web3-icon`
- Icon component is moved out from `<DynamicIcon />` in order to prevent mounting and unmounting on each render cycle
- `<DynamicIcon />` doesn't load all icons any more (it still initially loads bundle with icon aliases)
- each dynamic icon load separately as an individual chunk with the very little overhead
- do not create fallback component in `<SVG />` during rendering cycle

`apps/docs`
- create separate page to render one icon to make sure that it doesn't load unnecessary resources

Remaining tasks:
- [ ] generate static React component for every icon
- [ ] find a way to not load icon aliases
- [ ] refactor `<StaticIcon />` (transform state + useEffect into a derived state)

All icons are shipped as a huge bundle
Screenshot 2024-10-21 at 16 54 48
Screenshot 2024-10-21 at 16 55 30

Icons are loaded dynamically one by one
Screenshot 2024-10-21 at 16 58 21
Screenshot 2024-10-21 at 16 58 52

### CODE REVIEW

**Comment by Argeare5** [comment]
`generate static React component for every icon` - I don't think it makes much sense, we had it like that in the initial version, but it's completely inconvenient to use in most of our cases. @smbdy what do you think?

**Comment by smbdy** [comment]
For our specific usecases probably not, but for the sake of open sourcing this library it makes sense to support it, as it's common among popular icon libraries.

**Comment by Argeare5** [comment]
in this case i think we need to change configs for svg code generation, now we have objects with svg data, we should make components and then change logic for DynamicIcon.
we use `svg-to-ts` for this, so it shouldn't be a big problem https://www.npmjs.com/package/svg-to-ts @isArlekin

**Comment by isArlekin** [comment]
We've discussed it with @smbdy last week. Generating React components using svg is a next task

**Review by Argeare5 — APPROVED** [review]

**Pull request merged**
